"""Add size column on state

Revision ID: 877a6e9351ea
Revises: cdaec8965409
Create Date: 2026-03-20 09:57:01.162934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877a6e9351ea'
down_revision: Union[str, Sequence[str], None] = 'cdaec8965409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'cities', 'states', ['state_id'], ['id'])
    op.add_column('states', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'size')
    # op.drop_constraint(None, 'cities', type_='foreignkey')
    # ### end Alembic commands ###
