"""Create states table

Revision ID: cdaec8965409
Revises: 2cf1f42bb4f6
Create Date: 2026-03-20 09:37:00.436699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaec8965409'
down_revision: Union[str, Sequence[str], None] = '2cf1f42bb4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    # op.add_column('cities', sa.Column('state_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'cities', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'cities', type_='foreignkey')
    # op.drop_column('cities', 'state_id')
    op.drop_table('states')
    # ### end Alembic commands ###
